BBBBBBB BBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBB XXXXX BBBBBBBB BBBBBBBBBB
BBBBB BBBBBBBBBBBB 
XXXXXXXXXXXXXX
XXXXX XXXXXXXXX XXXXXXXXXXXXXX
    BBBBBBBBBB
    FFFFFF
    XXXXXX  XXXXXXXXXXXXX XXXXXXXXXX XXXX
XXXXXXX
BBBBBBBB BBBBBBBBBBBB