# Generated by Django 5.1.4 on 2025-05-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
